image:
  name: legendarydevs/sfdx_deploy
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD
  email: $DOCKER_HUB_EMAIL
pipelines:
  branches:
    master:
      - step:
        name: Deploy to Staging
        deployment: staging
        script:
          - echo 'Deploy to Staging'
          - chmod +x pipeline_deploy.sh
          - ./pipeline_deploy.sh $DEPLOY_KEY $SFDC_USERNAME $SFDC_CONSUMER_KEY $SFDC_URL
      - step:
        name: Deploy to Production
        deployment: production
        trigger: manual
        script:
          - echo 'Deploy to Production'
          - chmod +x pipeline_deploy.sh
          - ./pipeline_deploy.sh $DEPLOY_KEY $SFDC_USERNAME $SFDC_CONSUMER_KEY $SFDC_URL
    bugfix/*:
      - step:
        name: Validate Deploy
        script:
          - echo 'Validating deploy'
          - chmod +x pipeline_validate.sh
          - ./pipeline_validate.sh $DEPLOY_KEY $SFDC_USERNAME $SFDC_CONSUMER_KEY $SFDC_URL
    feature/*:
      - step:
        name: Validate Deploy
        script:
          - echo 'Validating deploy'
          - chmod +x pipeline_validate.sh
          - ./pipeline_validate.sh $DEPLOY_KEY $SFDC_USERNAME $SFDC_CONSUMER_KEY $SFDC_URL
    declarative/*:
      - step:
        name: Validate Deploy
        script:
          - echo 'Validating deploy'
          - chmod +x pipeline_validate.sh
          - ./pipeline_validate.sh $DEPLOY_KEY $SFDC_USERNAME $SFDC_CONSUMER_KEY $SFDC_URL
