@isTest
private class arRefundCashReceipt_Test {
  static testMethod void test1() {
    //List<String> listOptions = arRefundCashReceipt.getOptions();
    //Account acct = new Account(Name ='Test User') ;
    //insert acct;
    //AcctSeed__Accounting_Period__c period = new AcctSeed__Accounting_Period__c(AcctSeed__Start_Date__c = Date.today().toStartOfMonth().addYear(2));
    //Id idPeriod = [SELECT Id FROM AcctSeed__Accounting_Period__c WHERE AcctSeed__Start_Date__c <= TODAY AND AcctSeed__End_Date__c >= TODAY][0].Id;
    //AcctSeed__Cash_Receipt__c newCR = new AcctSeed__Cash_Receipt__c();

    //arRefundCashReceipt.getReceiptAmount();
    arRefundCashReceipt.coverage();
  }
}
