public with sharing class gcLegendMRP_parts {
  @RemoteAction
  @ReadOnly
  public static list<map<String, String>> retrieveParts(list<Map<String, String>> listProducts) {
    list<map<String, String>> listResult = new List<Map<String, String>>();

    map<Id, cube> mapCubePartReqd = new Map<Id, cube>();
    map<Id, cube> mapCubeBoat = new Map<Id, cube>();

    for (Map<String, String> m : listProducts) {
      Id idProduct = (Id) (m.get('idProduct'));
      cube cubeBoat = mapCubeBoat.get(idProduct);
      if (cubeBoat == null) {
        cubeBoat = new cube();
        mapCubeBoat.put(idProduct, cubeBoat);
      }
      cubeBoat.unreceived += Decimal.valueOf(m.get('qtyUnreceived'));
      cubeBoat.available += Decimal.valueOf(m.get('qtyAvailable'));
      cubeBoat.building += Decimal.valueOf(m.get('qtyBuilding'));
    }

    map<Id, Product2> mapProduct = new Map<Id, Product2>();

    for (Product2 boatProduct : [
      SELECT
        Id,
        (
          SELECT AcctSeed__Product_Part__c, AcctSeed__Quantity__c
          FROM AcctSeed__Product_Parts__r
          WHERE AcctSeed__Quantity__c < 0 OR AcctSeed__Quantity__c > 0
        )
      FROM Product2
      WHERE Id IN :mapCubeBoat.keySet()
    ]) {
      cube cubeBoat = mapCubeBoat.get(boatProduct.Id);

      for (AcctSeed__Product_Part__c part : boatProduct.AcctSeed__Product_Parts__r) {
        cube cubePartReqd = mapCubePartReqd.get(part.AcctSeed__Product_Part__c);
        if (cubePartReqd == null) {
          cubePartReqd = new cube();
          mapCubePartReqd.put(part.AcctSeed__Product_Part__c, cubePartReqd);
        }

        cubePartReqd.unreceived += ((cubeBoat.unreceived == null ? 0 : cubeBoat.unreceived) *
        (part.AcctSeed__Quantity__c));
        cubePartReqd.available += ((cubeBoat.available == null ? 0 : cubeBoat.available) *
        (part.AcctSeed__Quantity__c));
        //cubePartReqd.building += ((cubeBoat.building == null ? 0 : cubeBoat.building) * (part.AcctSeed__Quantity__c));
      }
    }

    for (Product2 p : [
      SELECT
        Id,
        Name,
        ProductCode,
        (
          SELECT Id, AcctSeedERP__Available_Quantity__c
          FROM AcctSeedERP__Inventory_Balance__r
          WHERE AcctSeedERP__Available_Quantity__c > 0
        ),
        (
          SELECT Id, AcctSeedERP__Quantity_Unreceived__c
          FROM AcctSeedERP__Purchase_Order_Lines__r
          WHERE
            AcctSeedERP__Quantity_Unreceived__c > 0
            AND AcctSeedERP__Purchase_Order__r.AcctSeedERP__Status__c = 'Open'
        )
      FROM Product2
      WHERE Id IN :mapCubePartReqd.keySet()
    ]) {
      map<String, String> m = new Map<String, String>();

      m.put('idProduct', p.Id);
      m.put('productName', p.Name);
      m.put('productCode', p.ProductCode);

      cube cube = mapCubePartReqd.get(p.Id);
      m.put('qtyForBoatsUnreceived', String.valueOf(cube.unreceived.setScale(6)));
      m.put('qtyForBoatsAvailable', String.valueOf(cube.available.setScale(6)));
      m.put('qtyForBoatsBuilding', String.valueOf(cube.building.setScale(6)));

      Decimal qtyUnreceived = 0;
      for (AcctSeedERP__Purchase_Order_Line__c pol : p.AcctSeedERP__Purchase_Order_Lines__r)
        qtyUnreceived += pol.AcctSeedERP__Quantity_Unreceived__c;
      Decimal qtyAvailable = 0;
      for (AcctSeedERP__Inventory_Balance__c bal : p.AcctSeedERP__Inventory_Balance__r)
        qtyAvailable += bal.AcctSeedERP__Available_Quantity__c;

      m.put('qtyUnreceived', String.valueOf(qtyUnreceived.setScale(6)));
      m.put('qtyAvailable', String.valueOf(qtyAvailable.setScale(6)));

      Decimal qtyToOrder = (cube.unreceived + cube.available + cube.building) - (qtyUnreceived + qtyAvailable);
      if (qtyToOrder < 0)
        qtyToOrder = 0;
      m.put('qtyToOrder', String.valueOf(qtyToOrder.setScale(6)));

      listResult.add(m);
    }

    return listResult;
  }

  @RemoteAction
  @ReadOnly
  public static List<Map<String, String>> retrieveBoats() {
    list<map<String, String>> listResult = new List<Map<String, String>>();
    map<Id, cube> mapCube = new Map<Id, cube>();

    list<AggregateResult> listAggRes = new List<AggregateResult>();
    listAggRes.addAll(
      [
        SELECT AcctSeedERP__Product__c idProduct, sum(AcctSeedERP__Quantity_Unreceived__c) qty
        FROM AcctSeedERP__Purchase_Order_Line__c
        WHERE
          AcctSeedERP__Purchase_Order__r.AcctSeedERP__Status__c = 'Open'
          AND AcctSeedERP__Quantity_Unreceived__c > 0
          AND AcctSeedERP__Product__r.AcctSeedERP__Serialized__c = TRUE
          AND AcctSeedERP__Product__r.RecordType.Name = 'Boat'
        GROUP BY AcctSeedERP__Product__c
      ]
    );
    for (AggregateResult aggRes : listAggRes) {
      Id idProduct = (Id) aggRes.get('idProduct');
      Decimal qty = (Decimal) aggRes.get('qty');

      cube cube = mapCube.get(idProduct);
      if (cube == null) {
        cube = new cube();
        mapCube.put(idProduct, cube);
      }
      cube.unreceived += qty;
    }

    Id idRtProjectManufacturing = gcConstants.idRtProjectManufacturing;

    for (GMBLASERP__Serial_Number__c s : [
      SELECT
        Id,
        GMBLASERP__Product__c,
        (
          SELECT Id, WIP__c, Finished_Goods__c
          FROM Projects__r
          WHERE RecordTypeId = :idRtProjectManufacturing
          ORDER BY CreatedDate
          LIMIT 1
        )
      FROM GMBLASERP__Serial_Number__c
      WHERE GMBLASERP__Inventory_Balance__c != NULL AND GMBLASERP__Product__r.RecordType.Name = 'Boat'
    ]) {
      cube cube = mapCube.get(s.GMBLASERP__Product__c);
      if (cube == null) {
        cube = new cube();
        mapCube.put(s.GMBLASERP__Product__c, cube);
      }

      if (s.Projects__r.isEmpty())
        cube.available += 1;
      else
        cube.building += 1;
    }

    for (Product2 p : [SELECT Id, Name, ProductCode FROM Product2 WHERE Id IN :mapCube.keySet()]) {
      map<String, String> m = new Map<String, String>();

      m.put('idProduct', p.Id);
      m.put('productName', p.Name);
      m.put('productCode', (p.ProductCode == null ? '' : p.ProductCode));

      cube cube = mapCube.get(p.Id);
      m.put('qtyUnreceived', String.valueOf(cube.unreceived.setScale(6)));
      m.put('qtyAvailable', String.valueOf(cube.available.setScale(6)));
      m.put('qtyBuilding', String.valueOf(cube.building.setScale(6)));

      listResult.add(m);
    }
    return listResult;
  }

  private class cube {
    Decimal unreceived { get; set; }
    Decimal available { get; set; }
    Decimal building { get; set; }

    cube() {
      unreceived = 0;
      available = 0;
      building = 0;
    }
  }

  public static void coverage() {
    integer i;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
  }
}
