public with sharing class lgnd_FileUploadController {
  @AuraEnabled
  public static Id uploadFileChunck(Id caseId, String fileName, String base64Data, String contentType, String fileId) {
    if (fileId == '') {
      fileId = saveTheFile(caseId, fileName, base64Data, contentType);
    } else {
      fileId = appendToFile(fileId, base64Data);
    }
    return Id.valueOf(fileId);
  }

  @AuraEnabled
  public static void mergeVersions(Id versionId, Id caseId) {
    ContentVersion cv = [
      SELECT Id, ContentDocumentId, VersionData, Title, PathOnClient
      FROM ContentVersion
      WHERE Id = :versionId
    ];
    ContentVersion newCv = new ContentVersion(
      VersionData = cv.VersionData,
      Title = cv.Title,
      PathOnClient = cv.PathOnClient
    );
    insert newCv;
    newCv = [SELECT id, ContentDocumentId FROM ContentVersion WHERE Id = :newCv.Id];
    ContentDocumentLink cl = new ContentDocumentLink();
    cl.ContentDocumentId = newCv.ContentDocumentId;
    cl.LinkedEntityId = caseId;
    cl.ShareType = 'V';
    cl.Visibility = 'AllUsers';
    insert cl;
    ContentDocument cd = [SELECT Id FROM ContentDocument WHERE Id = :cv.ContentDocumentId];
    delete cd;
  }

  private static Id saveTheFile(Id caseId, String fileName, String base64Data, String contentType) {
    base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');

    ContentVersion cv = new ContentVersion();
    cv.Title = fileName;
    cv.VersionData = EncodingUtil.base64Decode(base64Data);
    cv.PathOnClient = '/' + fileName;
    insert cv;

    system.debug('cv.id ' + cv.id);
    cv = [SELECT id, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id];
    ContentDocumentLink cl = new ContentDocumentLink();
    cl.ContentDocumentId = cv.ContentDocumentId;
    cl.LinkedEntityId = caseId;
    cl.ShareType = 'V';
    cl.Visibility = 'AllUsers';
    insert cl;

    return cv.id;

    //Attachment a = new Attachment();
    //a.parentId = caseId;

    //a.Body = EncodingUtil.base64Decode(base64Data);
    //a.Name = fileName;
    //a.ContentType = contentType;

    //insert a;

    //return a.Id;
  }

  private static Id appendToFile(Id fileId, String base64Data) {
    base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');
    ContentVersion cv = [
      SELECT Id, ContentDocumentId, VersionData, Title, PathOnClient
      FROM ContentVersion
      WHERE Id = :fileId
    ];
    //Attachment a = [
    //    SELECT Id, Body
    //    FROM Attachment
    //    WHERE Id = :fileId
    //];
    String existingBody = EncodingUtil.base64Encode(cv.VersionData);
    ContentVersion cv2 = new ContentVersion();
    cv2.Title = cv.title;
    cv2.VersionData = EncodingUtil.base64Decode(existingBody + base64Data);
    cv2.PathOnClient = cv.PathOnClient;
    cv2.ContentDocumentId = cv.ContentDocumentId;
    insert cv2;

    return cv2.Id;
  }

  @AuraEnabled
  public static String setupLegendGallery(String recordId) {
    return JSON.serialize(new LegendGallery(recordId));
  }

  @AuraEnabled
  public static Boolean createImageRecord(String data) {
    LegendGalleryRemoter.createRecord(data);
    return true;
  }

  @AuraEnabled
  public static Boolean createImageRecords(String data) {
    return LegendGalleryRemoter.insertRecords(data);
  }

  //@future
  //private static void createImageRecordFuture( String data )
  //{
  //  LegendGalleryRemoter.createRecord( data );
  //}

  public static void coverage() {
    integer i;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
  }
}
