@isTest
private class lgndPurchaseOrderLine_Test {
  //  @testSetup static void dataSetup()
  //  {
  //    new Factory_TestData();
  //    Factory_CustomSettings.setupInventorySettings();
  //  }
  //
  //	@isTest static void coverageTest() {
  //		lgndPurchaseOrderLine.coverage();
  //	}
  //
  //	@isTest static void triggerTest() {
  //		Product2 boat = Factory_Product.createNonSerializedProduct( 'Part', 'Electronics');
  //    AcctSeed__Ledger__c ledger = [SELECT Id FROM AcctSeed__Ledger__c LIMIT 1];
  //    AcctSeedERP__Purchase_Order__c po =  new AcctSeedERP__Purchase_Order__c(
  //      AcctSeedERP__Order_Date__c = date.Today(),
  //      AcctSeedERP__Ledger__c = ledger.Id
  //    );
  //    insert po;
  //    insert new AcctSeedERP__Purchase_Order_Line__c
  //    (
  //      AcctSeedERP__Product__c = boat.Id,
  //      AcctSeedERP__Purchase_Order__c = po.Id,
  //      AcctSeedERP__Quantity__c = 1,
  //      AcctSeedERP__Unit_Price__c = 1
  //    );
  //	}
}
