public with sharing class TruckSchedule {
  public class TruckScheduleException extends Exception {
  }

  public class EventData {
    public String id { get; set; }
    public String name { get; set; }
    public String driver { get; set; }
    public String truckDriverId { get; set; }
    public String truck { get; set; }
    public String trailer { get; set; }
    public Decimal distance { get; set; }
    public Date startDateTime { get; set; }
    public String startDate { get; set; }
    //public Date deliveryDateTime { get; set; }
    //public String deliveryDate { get; set; }
    public Date endDateTime { get; set; }
    public String endDate { get; set; }
    //public String destination { get; set; }
    //public Decimal travelDays { get; set; }
    //public Map<String, List<String>> loadContents { get; set; }

    //public EventData(Truck_Load__c tl)
    //{
    //  this.id = tl.Id;
    //  this.name = tl.Name;
    //  this.travelDays = tl.Travel_Days__c  <= 1 ? 1 : tl.Travel_Days__c;
    //  this.driver = tl.Driver__c;
    //  this.truck = tl.Truck__c;
    //  this.trailer = tl.Trailer__c;
    //  this.startDateTime = tl.Departure_Date2__c;
    //  this.startDate = dateToString( tl.Departure_Date2__c );
    //  this.deliveryDateTime = tl.Delivery_Date2__c;
    //  this.deliveryDate = dateToString( tl.Delivery_Date2__c );
    //  this.endDateTime = tl.Return_Date2__c;
    //  this.endDate = dateToString( tl.Return_Date2__c );
    //  this.destination = tl.Destination__c;
    //  if( tl.Truck_Load_Lines__r != null && tl.Truck_Load_Lines__r.size() > 0 )
    //  {
    //    buildLoadContents( tl.Truck_Load_Lines__r);
    //  }
    //}

    public EventData(Truck_Trip__c trip) {
      this.id = trip.Id;
      this.name = trip.Name;
      this.driver = trip.Driver__c;
      this.truckDriverId = trip.Truck_Driver__c;
      this.truck = trip.Truck__c;
      this.trailer = trip.Trailer__c;
      this.distance = trip.Distance_KM__c;
      this.startDateTime = trip.Departure_Date__c;
      this.startDate = dateToString(trip.Departure_Date__c);
      this.endDateTime = trip.Return_Date__c;
      this.endDate = dateToString(trip.Return_Date__c);
    }

    private String dateToString(Date d) {
      if (d != null) {
        return DateTime.newInstance(d.year(), d.month(), d.day()).format('MM/dd/yy');
      }
      return null;
    }

    //private void buildLoadContents( TruckLoadLine__c[] tlls )
    //{
    //  this.loadContents = new Map<String, List<String>>();
    //  for( String trailerPos : LGND_Utilities.getPicklistValues('TruckLoadLine__c', 'TruckPosition__c') )
    //  {
    //    this.loadContents.put( trailerPos, new List<String>() );
    //  }

    //  Map<Id, TruckLoadLine__c> truckLoadLineErpOrderMap = new Map<Id, truckLoadLine__c>();
    //  Set<Id> productRTs = new Set<Id>{
    //    LGND_Utilities.recordTypeIdFromName('Product2', 'Trailer'),
    //    LGND_Utilities.recordTypeIdFromName('Product2', 'Boat')
    //  };
    //  for( TruckLoadLine__c tll : tlls )
    //  {
    //    truckLoadLineErpOrderMap.put( tll.ERP_Order__c, tll );
    //  }
    //  AcctSeed__Project__c[] erps = [SELECT Id,
    //                                 (SELECT Id,
    //                                        AcctSeedERP__Product__r.RecordType.Name,
    //                                        Product_Name__c
    //                                  FROM AcctSeedERP__Project_Materials__r
    //                                  WHERE AcctSeedERP__Product__r.RecordTypeId IN :productRTs)
    //                                FROM AcctSeed__Project__c
    //                                WHERE Id IN :truckLoadLineErpOrderMap.keySet() ];
    //  for( AcctSeed__Project__c erp : erps )
    //  {
    //    String boatName = '';
    //    String trailerName = '';
    //    String result = '';
    //    for( AcctSeedERP__Material__c mat : erp.AcctSeedERP__Project_Materials__r )
    //    {
    //      if( mat.AcctSeedERP__Product__r.RecordType.Name == 'Boat' )
    //        boatName = mat.Product_Name__c;
    //      if( mat.AcctSeedERP__Product__r.RecordType.Name == 'Trailer' )
    //        trailerName = mat.Product_Name__c;
    //    }
    //    if( boatName != '' && boatName != 'Loose Items' )
    //      result += boatName + ' / ';
    //    result += trailerName;
    //    this.loadContents.get( truckLoadLineErpOrderMap.get(erp.Id).TruckPosition__c ).add( result );
    //  }
    //}
  }

  public Truck_Trip__c[] scheduables { get; set; }
  public Map<String, Boolean> crudPermissions { get; set; }
  public Map<String, Map<String, String>> truckDrivers { get; set; }

  public TruckSchedule() {
  }

  public TruckSchedule(ApexPages.StandardController std) {
    scheduables = fetchScheduables();
    truckDrivers = TruckSchedule.fetchTruckDrivers();
    setCrudPermissions();
  }

  public String getCrudPermissionsJSON() {
    return JSON.serialize(crudPermissions);
  }

  private void setCrudPermissions() {
    Schema.DescribeSObjectResult tripObj = Schema.sObjectType.Truck_Trip__c;
    Schema.DescribeSObjectResult destObj = Schema.sObjectType.Truck_Destination__c;
    Schema.DescribeSObjectResult matObj = Schema.sObjectType.AcctSeedERP__Material__c;
    crudPermissions = new Map<String, Boolean>();
    crudPermissions.put('canEditTrips', tripObj.isUpdateable());
    crudPermissions.put('canDeleteTrips', tripObj.isDeletable());
    crudPermissions.put('canCreateDestinations', destObj.isCreateable());
    crudPermissions.put('canEditDestinations', destObj.isUpdateable());
    crudPermissions.put('canDeleteDestinations', destObj.isDeletable());
    crudPermissions.put('canEditMaterials', matObj.isUpdateable());
  }

  public List<String> getDrivers() {
    return LGND_Utilities.getPicklistValues('Truck_Trip__c', 'Driver__c');
  }

  public String getTruckDriversJSON() {
    return JSON.serialize(truckDrivers);
  }

  public static Map<String, Map<String, String>> fetchTruckDrivers() {
    Map<String, Map<String, String>> drivers = new Map<String, Map<String, String>>();
    for (Truck_Driver__c td : [
      SELECT Id, Name, CalBgColor__c, CalBorderColor__c, CalTextColor__c
      FROM Truck_Driver__c
      ORDER BY Name DESC
    ]) {
      Map<String, String> details = new Map<String, String>();
      details.put('Id', td.Id);
      details.put('Name', td.Name);
      details.put('BgColor', td.CalBgColor__c);
      details.put('BorderColor', td.CalBorderColor__c);
      details.put('TextColor', td.CalTextColor__c);
      drivers.put(td.Id, details);
    }
    return drivers;
  }

  @RemoteAction
  @Readonly
  public static List<EventData> fetchAllTrips(Long startAt, Long endAt, Id truckDriverId) {
    Date sDateTime = DateTime.newInstance(startAt).date();
    Date eDateTime = DateTime.newInstance(endAt).date();
    System.debug(sDateTime);
    System.debug(eDateTime);
    List<EventData> result = new List<EventData>();
    List<Truck_Trip__c> trips = [
      SELECT
        Id,
        Name,
        Driver__c,
        Distance_KM__c,
        Truck_Driver__c,
        Truck__c,
        Trailer__c,
        Departure_Date__c,
        Return_Date__c
      FROM Truck_Trip__c
      WHERE Departure_Date__c >= :sDateTime AND Departure_Date__c <= :eDateTime AND Truck_Driver__c = :truckDriverId
    ];
    for (Truck_Trip__c trip : trips) {
      result.add(new EventData(trip));
    }
    return result;
  }

  @RemoteAction
  @Readonly
  public static Truck_Trip__c fetchTrip(String tripId) {
    return TripBuilderController.fetchTrip(Id.valueOf(tripId));
  }

  @RemoteAction
  public static EventData changedByDays(String tripId, Integer numDays) {
    if (Schema.sObjectType.Truck_Trip__c.isUpdateable()) {
      Truck_Trip__c trip = [
        SELECT Id, Distance_KM__c, Departure_Date__c, Return_Date__c, Truck__c, Trailer__c, Truck_Driver__c
        FROM Truck_Trip__c
        WHERE Id = :tripId
      ];
      trip.Departure_Date__c = trip.Departure_Date__c.addDays(numDays);
      trip.Return_Date__c = trip.Return_Date__c.addDays(numDays);
      String errorMsg = findSchedulingConflicts(trip);
      if (errorMsg != null)
        throw new TruckScheduleException(errorMsg);

      update trip;
      return new EventData(trip);
    }
    throw new TruckScheduleException('You do not have the required access on the Truck Trip object');
  }

  @RemoteAction
  public static EventData addedDays(String tripId, Integer numDays) {
    if (Schema.sObjectType.Truck_Trip__c.isUpdateable()) {
      Truck_Trip__c trip = [
        SELECT Id, Distance_KM__c, Departure_Date__c, Return_Date__c, Truck__c, Trailer__c, Truck_Driver__c
        FROM Truck_Trip__c
        WHERE Id = :tripId
      ];
      trip.Return_Date__c = trip.Return_Date__c.addDays(numDays);
      String errorMsg = findSchedulingConflicts(trip);
      if (errorMsg != null)
        throw new TruckScheduleException(errorMsg);

      update trip;
      return new EventData(trip);
    }
    throw new TruckScheduleException('You do not have the required access on the Truck Trip object');
  }

  @RemoteAction
  public static List<Truck_Trip__c> unschedule(String tripId) {
    if (Schema.sObjectType.Truck_Trip__c.isUpdateable()) {
      Truck_Trip__c trip = [SELECT Id FROM Truck_Trip__c WHERE Id = :tripId];
      trip.Driver__c = null;
      trip.Distance_KM__c = null;
      trip.Departure_Date__c = null;
      trip.Return_Date__c = null;
      trip.Truck__c = null;
      trip.Trailer__c = null;
      update trip;
      return fetchScheduables();
    }
    throw new TruckScheduleException('You do not have the required access on the Truck Trip object');
  }

  //@RemoteAction
  //public static List<Truck_Load__c> unschedule(String tlId)
  //{
  //  Truck_Load__c tl = [SELECT Id FROM Truck_Load__c WHERE Id = :tlId];
  //  tl.Departure_Date2__c = null;
  //  tl.Delivery_Date2__c = null;
  //  tl.Return_Date2__c = null;
  //  tl.Truck__c = null;
  //  tl.Trailer__c = null;
  //  update tl;
  //  return fetchScheduables();
  //}

  private static List<Truck_Trip__c> fetchScheduables() {
    if (Schema.sObjectType.Truck_Trip__c.isUpdateable()) {
      return [SELECT Id, Name, Truck__c, Trailer__c, Driver__c FROM Truck_Trip__c WHERE Departure_Date__c = NULL];
    }
    return null; //new List<Truck_Trip__c>();
  }

  public static String findSchedulingConflicts(Truck_Trip__c tt) {
    Truck_Driver__c driver = [
      SELECT Id, AllowSchedulingConflicts__c
      FROM Truck_Driver__c
      WHERE Id = :tt.Truck_Driver__c
    ];
    if (!driver.AllowSchedulingConflicts__c) {
      List<String> errors = new List<String>();
      Truck_Trip__c[] conflicts = [
        SELECT Id, Truck_Driver__c, Truck_Driver__r.Name, Trailer__c, Truck__c, Departure_Date__c, Return_Date__c
        FROM Truck_Trip__c
        WHERE
          Id != :tt.Id
          AND ((Return_Date__c >= :tt.Departure_Date__c
          AND Departure_Date__c <= :tt.Departure_Date__c)
          OR (Departure_Date__c <= :tt.Return_Date__c
          AND Return_Date__c >= :tt.Return_Date__c))
          AND (Truck_Driver__c = :tt.Truck_Driver__c
          OR Truck__c = :tt.Truck__c
          OR Trailer__c = :tt.Trailer__c)
      ];
      for (Truck_Trip__c conflict : conflicts) {
        if (tt.Truck_Driver__c != null && tt.Truck_Driver__c == conflict.Truck_Driver__c)
          errors.add(conflict.Truck_Driver__r.Name + ' is already scheduled');
        if (tt.Truck__c != null && tt.Truck__c == conflict.Truck__c)
          errors.add('Truck ' + tt.Truck__c + ' is already in use');
        if (tt.Trailer__c != null && tt.Trailer__c == conflict.Trailer__c)
          errors.add('Trailer ' + tt.Trailer__c + ' is already in use');
      }
      if (errors.size() > 0) {
        return String.join(errors, ', ');
      }
      return null;
    }
    return null;
  }

  public static void coverage() {
    integer i;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
  }
}
